#!/bin/bash

#SBATCH -p general
#SBATCH -N 1
#SBATCH --mem 4g
#SBATCH -n 2
#SBATCH -t 6:00:00
#SBATCH --mail-type=fail
#SBATCH --mail-user=prisca@live.unc.edu

# This script serves to obtain bin associations generated by the binning scripts (03-05), resulting in a table for each binning algorithm
# matching the contigs to their assigned bins.
# The resultant association tables are required for DAS_Tool to consolidate bins from the different algorithms.

# Input: Path to directory containing bins for each sample
#	1) concoct bins are located in: data/processed/binning/concoct/"$sample"/bins/*.fa
#	2) maxbin2 bins are located in: data/processed/binning/maxbin2/"$sample"/*.fasta
#	3) metabat2 bins are located in: data/processed/binning/metabat2/"$sample"/"$sample"_*.metabat-bins/*.fa

# Output: Bin association .txt files for each binning algorithm
#	1) concoct associations will be deposited as data/processed/binning/concoct/"$sample"/"$sample"_concoct_associations.txt
#	2) maxbin2 associations will be depositied as data/processed/binning/maxbin2/"$sample"/"$sample"_maxbin2_associations.txt
#	3) metabat2 associations will be depositied as data/processed/binning/metabat2/"$sample"/"$sample"_metabat2_associations.txt

sample=$1
concoct_dir=data/processed/binning/concoct
maxbin2_dir=data/processed/binning/maxbin2
metabat2_dir=data/processed/binning/metabat2

for bin_path in "$concoct_dir"/"$sample"/bins/*.fa; do
	bin_name=$(basename ${bin_path} .fa)
#	echo $bin_name
	grep ">" ${bin_path} | sed 's/>//g' | sed "s/$/\tconcoct.${bin_name}/g" >> "$concoct_dir"/"$sample"/"$sample"_concoct_associations.txt
done


for bin_path in "$maxbin2_dir"/"$sample"/*.fasta; do
        bin_name=$(basename ${bin_path} .fasta | sed "s/$sample.//g")
#	echo $bin_name
        grep ">" ${bin_path} | sed 's/>//g' | sed "s/$/\tmaxbin2.${bin_name}/g" >> "$maxbin2_dir"/"$sample"/"$sample"_maxbin2_associations.txt
done

for bin_path in "$metabat2_dir"/"$sample"/"$sample"_*.metabat-bins/*.fa; do
	bin_name=$(basename ${bin_path} .fa | sed 's/bin.//g') 
#	echo $bin_name
	grep ">" ${bin_path} | sed 's/>//g' | sed "s/$/\tmetabat2.${bin_name}/g" >> "$metabat2_dir"/"$sample"/"$sample"_metabat2_associations.txt
done
